import csv
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from make_tables import OPEN, SHORT, TASK_LABEL

TDIR = HERE.parent / "paper" / "tables"
HEADER = "% AUTO-GENERATED by analysis/make_appendix_tables.py -- do not edit by hand\n"
DISCOVERY = {"semeval_stance", "implicit_hate", "discourse"}

def read(name):
    return list(csv.DictReader((HERE / name).open()))

def write(name, text):
    (TDIR / name).write_text(HEADER + text)

def f(x, nd=3):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return "--"

def full_results():
    cells = {(r["task"], r["model"]): r for r in read("cell_metrics.csv")}
    boot = {(r["task"], r["model"]): r for r in read("bootstrap_cells.csv")}
    models = ["jev", "local_rlcd-0.6b", "local_qwen3-base"] + list(OPEN) + sorted(
        m for t, m in cells if cells[(t, m)]["kind"] == "llm")
    models = list(dict.fromkeys(models))
    tasks = sorted({t for t, _ in cells}, key=lambda t: TASK_LABEL[t])
    caption = (r"\caption{Complete per-cell results: accuracy, macro-F1, ECE (15 bins), "
               r"Brier, measured \$/1{,}000 items, and, for each LLM, the Jev-minus-LLM $\Delta$F1 "
               r"(points) with paired-bootstrap 95\% CI and BH-FDR $q$ ($^{*}$: significant at "
               r"$q=0.05$). $^{d}$ marks pilot tasks; -- marks the tropes cells unrunnable for "
               r"the 0.6B models and cells without a Jev comparison; $^{\dagger}$ marks open decision "
               r"systems added after the analysis plan was filed (Appendix~\ref{app:exploratory}), "
               r"which run locally at no API cost and cover 17 tasks (SemIf 16).}\label{tab:full}\\")
    hdr = r"Task & Model & Acc & F1 & ECE & Brier & \$/1k & $\Delta$F1 [95\% CI] & $q$ \\"
    lines = [r"\begin{longtable}{llrrrrrlr}", caption, r"\toprule", hdr, r"\midrule",
             r"\endfirsthead", r"\toprule", hdr, r"\midrule", r"\endhead",
             r"\bottomrule", r"\endfoot"]
    for t in tasks:
        label = TASK_LABEL[t] + ("$^{d}$" if t in DISCOVERY else "")
        for i, m in enumerate(models):
            r = cells.get((t, m))
            if r is None:
                continue
            cost1k = float(r["cost"]) / float(r["n"]) * 1000 if r["cost"] else None
            b = boot.get((t, m))
            if b:
                delta = f"${float(b['delta_f1'])*100:+.1f}$ [{float(b['ci_lo'])*100:+.1f}, {float(b['ci_hi'])*100:+.1f}]"
                q = f(b["q_bh"]) + (r"$^{*}$" if b["sig_q05"] == "1" else "")
            else:
                delta, q = "--", "--"
            lines.append(" & ".join([
                label if i == 0 else "", SHORT[m], f(r["acc"]), f(r["macro_f1"]),
                f(r["ece"]), f(r["brier"]), f(cost1k), delta, q]) + r" \\")
        lines.append(r"\midrule")
    lines[-1] = r"\end{longtable}"
    write("full_results.tex", "\n".join(lines) + "\n")

def exclusions_full():
    rows = [r for r in read("exclusions.csv")
            if any(int(r[k]) for k in ("api_gap", "empty_text", "invalid",
                                       "conf_absent", "conf_negative", "conf_oob"))]
    caption = (r"\caption{Per task and model exclusion counts, all cells with a nonzero count "
               r"(columns as in Table~\ref{tab:exclusions}; C.\ = confidence).}"
               r"\label{tab:exclusions_full}\\")
    hdr = r"Task & Model & API & Empty & Invalid & C.\ abs & C.\ neg & C.\ oob \\"
    lines = [r"\begin{longtable}{llrrrrrr}", caption, r"\toprule", hdr, r"\midrule",
             r"\endfirsthead", r"\toprule", hdr, r"\midrule", r"\endhead",
             r"\bottomrule", r"\endfoot"]
    for r in sorted(rows, key=lambda r: (TASK_LABEL[r["task"]], SHORT[r["model"]])):
        lines.append(" & ".join([TASK_LABEL[r["task"]], SHORT[r["model"]], r["api_gap"],
                                 r["empty_text"], r["invalid"], r["conf_absent"],
                                 r["conf_negative"], r["conf_oob"]]) + r" \\")
    lines.append(r"\end{longtable}")
    write("exclusions_full.tex", "\n".join(lines) + "\n")

def robustness():
    rows = read("robustness_conf_line.csv")
    models = sorted({r["model"] for r in rows}, key=lambda m: SHORT[m])
    tasks = sorted({r["task"] for r in rows})
    by = {(r["model"], r["task"]): float(r["delta"]) * 100 for r in rows}
    lines = [r"\begin{tabular}{l" + "r" * len(tasks) + "}", r"\toprule",
             "Model & " + " & ".join(TASK_LABEL[t] for t in tasks) + r" \\", r"\midrule"]
    for m in models:
        lines.append(SHORT[m] + " & " +
                     " & ".join(f"{by[(m, t)]:+.1f}" if (m, t) in by else "--" for t in tasks) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("robustness_conf_line.tex", "\n".join(lines) + "\n")

def simple(src, out, cols, headers, sort_key=None, fmt=None):
    rows = read(src)
    if sort_key:
        rows.sort(key=sort_key)
    lines = [r"\begin{tabular}{l" + "r" * (len(cols) - 1) + "}", r"\toprule",
             " & ".join(headers) + r" \\", r"\midrule"]
    for r in rows:
        vals = [(fmt or {}).get(c, lambda v: v)(r[c]) for c in cols]
        lines.append(" & ".join(str(v) for v in vals) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(out, "\n".join(lines) + "\n")

def name(m):
    return SHORT.get(m, m)

def b_tables():
    simple("b1_binning.csv", "b1_binning.tex",
           ["model", "ece_w10", "ece_w15", "ece_w20", "ece_m15"],
           ["Model", "10 bins", "15 bins (primary)", "20 bins", "15 equal-mass"],
           sort_key=lambda r: float(r["ece_w15"]), fmt={"model": name})
    simple("b2_temp_scaling.csv", "b2_temp_scaling.tex",
           ["model", "T", "median_ece_before", "median_ece_after"],
           ["Model", "$T$", "ECE before", "ECE after"],
           sort_key=lambda r: float(r["median_ece_after"]), fmt={"model": name})
    simple("b3_position_bias.csv", "b3_position_bias.tex",
           ["model", "n", "share_first_pred", "share_first_gold", "tv_distance"],
           ["Model", "$n$", "First opt.\\ (pred)", "First opt.\\ (gold)", "TV dist."],
           sort_key=lambda r: -float(r["tv_distance"]), fmt={"model": name})
    simple("b4_conf_vs_ptop.csv", "b4_conf_vs_ptop.tex",
           ["task", "ece_conf", "ece_ptop"],
           ["Task", "ECE (confidence)", "ECE ($p_{\\mathrm{top}}$)"],
           fmt={"task": lambda t: TASK_LABEL.get(t, t)})
    simple("b6_vs_2023.csv", "b6_vs_2023.tex",
           ["task", "model", "n", "both_correct", "only_2026", "only_2023", "neither"],
           ["Task", "Model", "$n$", "Both", "Only 2026", "Only 2023", "Neither"],
           sort_key=lambda r: (TASK_LABEL[r["task"]], r["model"]), fmt={"task": lambda t: TASK_LABEL.get(t, t), "model": name})
    simple("b8_cascade_sensitivity.csv", "b8_cascade_sensitivity.tex",
           ["llm", "t", "cost_scenario", "median_cost_fraction"],
           ["Partner", "$t$", "Scenario", "Median cost fraction"],
           fmt={"llm": name, "cost_scenario": lambda s: s.replace("_", r"\_")})
    simple("b8_human_review.csv", "b8_human_review.tex",
           ["t", "usd_per_item_human", "median_accuracy", "median_cost_per_1k"],
           ["$t$", "\\$/item human", "Median accuracy", "Median \\$/1k"])
    simple("b9_per_class_f1.csv", "b9_per_class_f1.tex",
           ["task", "model", "class", "support", "precision", "recall", "f1"],
           ["Task", "Model", "Class", "Support", "P", "R", "F1"],
           fmt={"task": lambda t: TASK_LABEL.get(t, t), "model": name,
                "class": lambda c: c.replace("_", r"\_")})
    simple("b5_confusion_tropes_top.csv", "b5_confusion_tropes_top.tex",
           ["gold", "pred", "count"], ["Gold trope", "Predicted trope", "Count"],
           fmt={"gold": lambda c: c.replace("_", r"\_"), "pred": lambda c: c.replace("_", r"\_")})
    for task in ["talklife", "conv_go_awry", "implicit_hate"]:
        rows = list(csv.reader((HERE / f"b5_confusion_{task}.csv").open()))
        hdr, body = rows[0], rows[1:]
        esc = lambda s: s.replace("_", r"\_").replace("\\pred", " $\\to$ ")
        lines = [r"\begin{tabular}{l" + "r" * (len(hdr) - 1) + "}", r"\toprule",
                 " & ".join(esc(h) for h in hdr) + r" \\", r"\midrule"]
        for r in body:
            lines.append(" & ".join([esc(r[0])] + r[1:]) + r" \\")
        lines += [r"\bottomrule", r"\end{tabular}"]
        write(f"b5_confusion_{task}.tex", "\n".join(lines) + "\n")

if __name__ == "__main__":
    full_results()
    exclusions_full()
    robustness()
    b_tables()
    print("appendix tables written to", TDIR)
