import csv
import json
import pathlib
import statistics
from collections import defaultdict

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
TDIR = ROOT / "paper" / "tables"
TDIR.mkdir(exist_ok=True)

SHORT = {
    "jev": "Jev", "local_rlcd-0.6b": "Qwen3-0.6B-RLCD", "local_qwen3-base": "Qwen3-0.6B base",
    "anthropic_claude-haiku-4.5": "Haiku 4.5", "anthropic_claude-sonnet-5": "Sonnet 5",
    "anthropic_claude-opus-5": "Opus 5", "anthropic_claude-fable-5.1": "Fable 5.1",
    "google_gemini-3.5-flash-lite": "Gem FL", "google_gemini-3.8-flash": "Gem 3.8F",
    "google_gemini-3.1-pro-preview": "Gem 3.1P", "google_gemma-4-31b-it": "Gemma 31B",
    "meta-llama_llama-4-scout": "L4 Scout", "meta-llama_llama-4-maverick": "L4 Mav",
    "mistralai_mistral-medium-3-5": "Mistral M", "moonshotai_kimi-k2.6": "Kimi 2.6",
    "openai_gpt-5.6-luna": "Luna", "openai_gpt-5.6-sol": "Sol",
    "openai_gpt-5.6-terra": "Terra", "openai_gpt-oss-120b": "OSS 120B",
    "deepseek_deepseek-v3.2": "DS V3.2", "qwen_qwen3-235b-a22b-2507": "Qwen 235B",
    "z-ai_glm-5.3": "GLM 5.3",
}
TASK_LABEL = {
    "indian_english_dialect": "Dialect", "emotion": "Emotion", "flute": "Figurative",
    "reddit_humor": "Humor", "ibc": "Ideology (utt.)", "implicit_hate": "Impl. Hate",
    "mrf": "Misinfo", "raop": "Persuasion (utt.)", "tempowic": "Sem. Change",
    "semeval_stance": "Stance", "discourse": "Discourse", "talklife": "Empathy",
    "persuasion": "Persuasion (conv.)", "wiki_politeness": "Politeness",
    "wiki_corpus": "Power", "conv_go_awry": "Toxicity",
    "media_ideology": "Ideology (doc.)", "tropes": "Tropes",
}
FAM_ORDER = {"utterance": 0, "conversation": 1, "document": 2}

ZIEMS = {
    "indian_english_dialect": (3.3, 3.0, 23.2), "emotion": (16.7, 71.6, 50.6),
    "flute": (25.0, 99.2, 17.5), "reddit_humor": (49.5, 73.1, 61.3),
    "ibc": (33.3, 64.8, 60.0), "implicit_hate": (16.7, 62.5, 3.7),
    "mrf": (50.0, 81.6, 26.9), "raop": (14.3, 52.0, 56.4),
    "tempowic": (50.0, 62.3, 21.2), "semeval_stance": (33.3, 36.1, 76.0),
    "discourse": (14.3, 49.6, 16.7), "talklife": (33.3, 71.6, 6.4),
    "persuasion": (50.0, 33.3, 28.6), "wiki_politeness": (33.3, 75.8, 59.7),
    "wiki_corpus": (49.5, 72.7, 42.0), "conv_go_awry": (50.0, 64.6, 55.4),
    "media_ideology": (33.3, 85.1, 51.5), "tropes": (36.9, None, 44.9),
}

cells = list(csv.DictReader((HERE / "cell_metrics.csv").open()))
by = {(r["task"], r["model"]): r for r in cells}
models = ["jev", "local_rlcd-0.6b", "local_qwen3-base"] + sorted(
    {r["model"] for r in cells if r["kind"] == "llm"})
tasks = sorted({r["task"] for r in cells},
               key=lambda t: (FAM_ORDER[by[(t, "jev")]["family"]], TASK_LABEL[t]))

def fmt(x, scale=100, nd=1):
    return "--" if x is None or x != x else f"{x * scale:.{nd}f}"

lines = [
    "% AUTO-GENERATED by analysis/make_tables.py -- do not edit by hand",
    r"\begin{tabular}{l" + "r" * (3 + len(models)) + "}",
    r"\toprule",
    " & \\multicolumn{3}{c}{Ziems et al.\\ (2023 runs)} & \\multicolumn{"
    + str(len(models)) + "}{c}{2026 runs (ours)} \\\\",
    r"\cmidrule(lr){2-4}\cmidrule(lr){5-" + str(4 + len(models)) + "}",
    "Task & Rand & FT & GPT-4 & "
    + " & ".join(r"\rot{" + SHORT[m] + "}" for m in models) + r" \\",
]
prev_fam = None
for t in tasks:
    fam = by[(t, "jev")]["family"]
    if fam != prev_fam:
        lines.append(r"\midrule")
        lines.append(r"\multicolumn{" + str(4 + len(models)) + r"}{l}{\itshape "
                     + fam.capitalize() + r"-level tasks} \\")
        prev_fam = fam
    rz, ft, g4 = ZIEMS[t]
    vals = []
    best = max((float(by[(t, m)]["macro_f1"]) for m in models if (t, m) in by))
    for m in models:
        r = by.get((t, m))
        if r is None:
            vals.append("--")
            continue
        v = float(r["macro_f1"])
        s = f"{v * 100:.1f}"
        vals.append(r"\textbf{" + s + "}" if v == best else s)
    star = r"$^{d}$" if by[(t, "jev")]["split"] == "discovery" else ""
    lines.append(TASK_LABEL[t] + star + f" & {fmt(rz/100)} & {fmt(ft/100 if ft else None)} & "
                 f"{fmt(g4/100)} & " + " & ".join(vals) + r" \\")
lines += [r"\bottomrule", r"\end{tabular}"]
(TDIR / "main_results.tex").write_text("\n".join(lines) + "\n")

conf = [r for r in cells if r["split"] == "confirmatory"]
lines = ["% AUTO-GENERATED by analysis/make_tables.py",
         r"\begin{tabular}{lrrrrr}", r"\toprule",
         r"Model & Med.\ ECE & Med.\ Brier & Med.\ AUC & Acc@0.9 & Cov@0.9 \\",
         r"\midrule"]
med_rows = []
for m in models:
    sub = [r for r in conf if r["model"] == m]
    def med(k):
        vals = [float(r[k]) for r in sub if r[k] and float(r[k]) == float(r[k])]
        return statistics.median(vals) if vals else float("nan")
    med_rows.append((med("ece"), SHORT[m], med("brier"), med("auc"),
                     med("acc0.9"), med("cov0.9")))
for e, name, b, a, a9, c9 in sorted(med_rows):
    row = " & ".join("--" if v != v else f"{v:.3f}" for v in (e, b, a, a9, c9))
    lines.append(f"{name} & {row} \\\\")
lines += [r"\bottomrule", r"\end{tabular}"]
(TDIR / "calibration.tex").write_text("\n".join(lines) + "\n")

lines = ["% AUTO-GENERATED by analysis/make_tables.py",
         r"\begin{tabular}{lrr}", r"\toprule",
         r"Model & \$/1{,}000 items & Total grid cost (USD) \\", r"\midrule"]
for m in models:
    sub = [r for r in cells if r["model"] == m]
    tot = sum(float(r["cost"]) for r in sub)
    n = sum(int(r["n"]) for r in sub)
    per1k = tot / n * 1000
    label = SHORT[m] + (r" (local)" if m.startswith("local_") else "")
    lines.append(f"{label} & {per1k:.3f} & {tot:.2f} \\\\")
lines += [r"\bottomrule", r"\end{tabular}"]
(TDIR / "cost.tex").write_text("\n".join(lines) + "\n")

exc = list(csv.DictReader((HERE / "exclusions.csv").open()))
lines = ["% AUTO-GENERATED by analysis/make_tables.py",
         r"\begin{tabular}{lrrrrr}", r"\toprule",
         r"Model & API gap & Empty & Invalid & Conf.\ absent & Conf.\ negative \\",
         r"\midrule"]
for m in models:
    sub = [r for r in exc if r["model"] == m]
    s = lambda k: sum(int(r[k]) for r in sub)
    lines.append(f"{SHORT[m]} & {s('api_gap')} & {s('empty_text')} & "
                 f"{s('invalid')} & {s('conf_absent')} & {s('conf_negative')} \\\\")
lines += [r"\bottomrule", r"\end{tabular}"]
(TDIR / "exclusions.tex").write_text("\n".join(lines) + "\n")

info = defaultdict(lambda: {"resolved": set(), "providers": set()})
for f in (ROOT / "results" / "pilot").glob("*.jsonl"):
    parts = f.stem.split("__")
    model = "jev" if len(parts) == 1 else parts[1]
    if len(parts) == 2 and not parts[1].startswith("local_"):
        continue
    for line in f.open():
        r = json.loads(line)
        info[model]["resolved"].add(pathlib.Path(str(r["model_resolved"])).name)
        if r.get("provider"):
            info[model]["providers"].add(r["provider"])
route = lambda m: ("decisions API" if m == "jev"
                   else "local (HF)" if m.startswith("local_") else "chat completions")
lines = ["% AUTO-GENERATED by analysis/make_tables.py",
         r"\begin{tabular}{llll}", r"\toprule",
         r"Model & Resolved version(s) & Provider(s) & Route \\", r"\midrule"]
for m in models:
    res = r"\,/\,".join(sorted(info[m]["resolved"])).replace("_", r"\_")
    prov = ", ".join(sorted(info[m]["providers"])) or "--"
    lines.append(f"{SHORT[m]} & \\texttt{{{res}}} & {prov} & {route(m)} \\\\")
lines += [r"\bottomrule", r"\end{tabular}"]
(TDIR / "reproducibility.tex").write_text("\n".join(lines) + "\n")

print("wrote", ", ".join(p.name for p in sorted(TDIR.glob("*.tex"))))
