import csv
import pathlib
import statistics
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from scores import DISCOVERY, FAMILY, ece, macro_f1

TASK_LABEL = {
    "indian_english_dialect": "Dialect", "emotion": "Emotion", "flute": "Figurative",
    "reddit_humor": "Humor", "ibc": "Ideology (utt.)", "implicit_hate": "Impl. Hate",
    "mrf": "Misinfo", "raop": "Persuasion (utt.)", "tempowic": "Sem. Change",
    "semeval_stance": "Stance", "discourse": "Discourse", "talklife": "Empathy",
    "persuasion": "Persuasion (conv.)", "wiki_politeness": "Politeness",
    "wiki_corpus": "Power", "conv_go_awry": "Toxicity",
    "media_ideology": "Ideology (doc.)", "tropes": "Tropes",
}

MODELS = [
    ("jev", "Jev"),
    ("local_rlcd-0.6b", "RLCD-0.6B"),
    ("local_qwen3-base", "Base-0.6B"),
    ("local_laya", "Laya-0.4B"),
    ("local_decider-0.8b", "decider-0.8b"),
    ("local_decider-2b", "decider-2b"),
    ("local_semif-4b", "SemIf-4B"),
    ("local_nimble-9b", "Nimble-9B"),
]

def main():
    rows = [r for r in csv.DictReader((HERE / "items.csv").open())
            if r["model"] in dict(MODELS)]
    by = {}
    for r in rows:
        by.setdefault((r["task"], r["model"]), []).append(r)

    cells = {}
    for (task, model), items in by.items():
        golds = [r["gold"] for r in items]
        preds = [str(r["pred"]) for r in items]
        valid = [r for r in items if r["valid"] == "1" and r["conf_status"] == "ok"]
        cells[(task, model)] = dict(
            task=task, model=model, n=len(items),
            f1=macro_f1(golds, preds),
            ece=ece([float(r["conf"]) for r in valid], [int(r["correct"]) for r in valid]),
            brier=statistics.mean(float(r["brier"]) for r in valid),
        )

    with (HERE / "open_models.csv").open("w", newline="") as fh:
        w = csv.DictWriter(fh, ["task", "model", "n", "f1", "ece", "brier"])
        w.writeheader()
        for k in sorted(cells):
            w.writerow(cells[k])

    tasks = sorted({t for t, _ in cells if t != "tropes"},
                   key=lambda t: ({"utterance": 0, "conversation": 1, "document": 2}[FAMILY[t]],
                                  TASK_LABEL[t]))
    slugs = [m for m, _ in MODELS]

    def cell(t, m, key, scale, nd):
        c = cells.get((t, m))
        return "--" if c is None else f"{c[key] * scale:.{nd}f}"

    lines = ["% AUTO-GENERATED by analysis/open_models.py -- do not edit by hand",
             r"\begin{tabular}{l" + "r" * len(MODELS) + "}", r"\toprule",
             "Task & " + " & ".join(label for _, label in MODELS) + r" \\", r"\midrule"]
    for t in tasks:
        mark = r"$^{d}$" if t in DISCOVERY else ""
        lines.append(TASK_LABEL[t] + mark + " & "
                     + " & ".join(cell(t, m, "f1", 100, 1) for m in slugs) + r" \\")
    lines.append(r"\midrule")
    for key, label, scale, nd in [("f1", "Median F1", 100, 1),
                                  ("ece", "Median ECE", 1, 3),
                                  ("brier", "Median Brier", 1, 3)]:
        meds = []
        for m in slugs:
            vals = [cells[(t, m)][key] for t in tasks
                    if t not in DISCOVERY and (t, m) in cells]
            meds.append(f"{statistics.median(vals) * scale:.{nd}f}" if vals else "--")
        lines.append(label + " & " + " & ".join(meds) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    out = HERE.parent / "paper" / "tables" / "b11_open_models.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")
    for m in slugs:
        n = sum(1 for t in tasks if (t, m) in cells)
        print(f"  {m}: {n}/{len(tasks)} tasks")

if __name__ == "__main__":
    main()
